TRP_LISTE_SOUNDS = {
	["Cat : Miaulement 1"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_01",["Categorie"] = "Cat",},
	["Cat : Miaulement 2"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_02",["Categorie"] = "Cat",},
	["Cat : Miaulement 3"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_03",["Categorie"] = "Cat",},
	["Cat : Miaulement 4"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_04",["Categorie"] = "Cat",},
	["Cat : Miaulement 5"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_05",["Categorie"] = "Cat",},
	["Cat : Miaulement 6"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_06",["Categorie"] = "Cat",},
	["Cat : Miaulement 7"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_07",["Categorie"] = "Cat",},
	["Cat : Miaulement 8"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_08",["Categorie"] = "Cat",},
	["Cat : Miaulement 9"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Cat_09",["Categorie"] = "Cat",},
	["Cat : Souffle"] = {["Url"] = "Sound\\Creature\\Cat\\CatAggro",["Categorie"] = "Cat",},
	["Cat : Miaulement 10"] = {["Url"] = "Sound\\Creature\\Cat\\CatStepA",["Categorie"] = "Cat",},
	["Cat : Miaulement 11"] = {["Url"] = "Sound\\Creature\\Cat\\CatStepB",["Categorie"] = "Cat",},
	["Cat : Miaulement 12"] = {["Url"] = "Sound\\Creature\\Cat\\CatStepC",["Categorie"] = "Cat",},
	["Pig : Grouinement 1"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_01",["Categorie"] = "Pig",},
	["Pig : Grouinement 2"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_02",["Categorie"] = "Pig",},
	["Pig : Grouinement 3"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_03",["Categorie"] = "Pig",},
	["Pig : Grouinement 4"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_04",["Categorie"] = "Pig",},
	["Pig : Grouinement 5"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_05",["Categorie"] = "Pig",},
	["Pig : Grouinement 6"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_06",["Categorie"] = "Pig",},
	["Pig : Grouinement 7"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_07",["Categorie"] = "Pig",},
	["Pig : Grouinement 8"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Pig_08",["Categorie"] = "Pig",},
	["Puppy : Jappement 1"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_01",["Categorie"] = "Dog",},
	["Puppy : Jappement 2"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_02",["Categorie"] = "Dog",},
	["Puppy : Jappement 3"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_03",["Categorie"] = "Dog",},
	["Puppy : Jappement 4"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_04",["Categorie"] = "Dog",},
	["Puppy : Jappement 5"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_05",["Categorie"] = "Dog",},
	["Puppy : Jappement 6"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_06",["Categorie"] = "Dog",},
	["Puppy : Jappement 7"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_07",["Categorie"] = "Dog",},
	["Puppy : Jappement 8"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_08",["Categorie"] = "Dog",},
	["Puppy : Jappement 9"] = {["Url"] = "Sound\\Emitters\\Emitter_Dalaran_Petstore_Puppy_09",["Categorie"] = "Dog",},
	["Ice : Craquement 1"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_01",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 2"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_02",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 3"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_03",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 4"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_04",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 5"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_05",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 6"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_06",["Categorie"] = "Ambiance : Ice",},
	["Ice : Craquement 7"] = {["Url"] = "Sound\\Emitters\\Emitter_IceCracking_07",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 1"] = {["Url"] = "Sound\\Spells\\IceVeinsA",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 2"] = {["Url"] = "Sound\\Spells\\IceVeinsB",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 3"] = {["Url"] = "Sound\\Spells\\IceVeinsC",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 4"] = {["Url"] = "Sound\\Spells\\IceVeinsD",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 5"] = {["Url"] = "Sound\\Spells\\IceVeinsE",["Categorie"] = "Ambiance : Ice",},
	["Ice : Refroidissement 6"] = {["Url"] = "Sound\\Spells\\IceVeinsF",["Categorie"] = "Ambiance : Ice",},
	["Alchemy : Préparation 1"] = {["Url"] = "Sound\\Doodad\\AK_AlchemyBottle01",["Categorie"] = "Alchemy",},
	["Alchemy : Préparation 2"] = {["Url"] = "Sound\\Doodad\\AK_AlchemySet01",["Categorie"] = "Alchemy",},
	["Alchemy : Préparation 3"] = {["Url"] = "Sound\\Doodad\\G_AlchemySet01",["Categorie"] = "Alchemy",},
	["Alchemy : Réaction 1"] = {["Url"] = "Sound\\Spells\\TradeSkills\\AlchemyCompleteA",["Categorie"] = "Alchemy",},
	["Alchemy : Artisanat 1"] = {["Url"] = "Sound\\Spells\\TradeSkills\\AlchemyCraftingA",["Categorie"] = "Alchemy",},
	["Alchemy : Artisanat 2"] = {["Url"] = "Sound\\Spells\\TradeSkills\\AlchemyCraftingB",["Categorie"] = "Alchemy",},
	["Alchemy : Artisanat 3"] = {["Url"] = "Sound\\Spells\\TradeSkills\\AlchemyCraftingC",["Categorie"] = "Alchemy",},
	["Ogre : Victoire 1"] = {["Url"] = "Sound\\Event Sounds\\OgreEventCheer1",["Categorie"] = "Cris",},
	["Ogre : Victoire 2"] = {["Url"] = "Sound\\Event Sounds\\OgreEventCheer2",["Categorie"] = "Cris",},
	["Ogre : Victoire 3"] = {["Url"] = "Sound\\Event Sounds\\OgreEventCheer3",["Categorie"] = "Cris",},
	["Ogre : Victoire 4"] = {["Url"] = "Sound\\Event Sounds\\OgreEventCheerUnique",["Categorie"] = "Cris",},
	["Alliance : Encouragement 1"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheer1_Alliance",["Categorie"] = "Cris",},
	["Alliance : Encouragement 2"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheer2_Alliance",["Categorie"] = "Cris",},
	["Alliance : Encouragement 3"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheerCrescendo_Alliance",["Categorie"] = "Cris",},
	["Alliance : Encouragement 4"] = {["Url"] = "Sound\\Events\\Arena_CrowdWalla_Alliance",["Categorie"] = "Cris",},
	["Horde : Encouragement 1"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheer1_Horde",["Categorie"] = "Cris",},
	["Horde : Encouragement 2"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheer2_Horde",["Categorie"] = "Cris",},
	["Horde : Encouragement 3"] = {["Url"] = "Sound\\Events\\Arena_CrowdCheerCrescendo_Horde",["Categorie"] = "Cris",},
	["Horde : Encouragement 4"] = {["Url"] = "Sound\\Events\\Arena_CrowdWalla_Horde",["Categorie"] = "Cris",},
	["Crowd : Panic 1"] = {["Url"] = "Sound\\Events\\EbonHold_CrowdScream1",["Categorie"] = "Cris",},
	["Crowd : Panic 2"] = {["Url"] = "Sound\\Events\\EbonHold_CrowdScream2",["Categorie"] = "Cris",},
	["Crowd : Panic 3"] = {["Url"] = "Sound\\Events\\EbonHold_CrowdScream3",["Categorie"] = "Cris",},
	["Crowd : Panic 4"] = {["Url"] = "Sound\\Events\\EbonHold_CrowdScream4",["Categorie"] = "Cris",},
	["Action : Coupe 1"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut1",["Categorie"] = "Barbier",},
	["Action : Coupe 2"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut2",["Categorie"] = "Barbier",},
	["Action : Coupe 3"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut3",["Categorie"] = "Barbier",},
	["Action : Coupe 4"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut4",["Categorie"] = "Barbier",},
	["Action : Coupe 5"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut5",["Categorie"] = "Barbier",},
	["Action : Coupe 6"] = {["Url"] = "Sound\\Interface\\BarberShop_Haicut6",["Categorie"] = "Barbier",},
	["Action : s'assoir 1"] = {["Url"] = "Sound\\Interface\\BarberShop_Sit1",["Categorie"] = "Mobilier",},
	["Action : s'assoir 2"] = {["Url"] = "Sound\\Interface\\BarberShop_Sit2",["Categorie"] = "Mobilier",},
	["Action : s'assoir 3"] = {["Url"] = "Sound\\Interface\\BarberShop_Sit3",["Categorie"] = "Mobilier",},
	["Bag : Sac"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpBag",["Categorie"] = "Equipement",},
	["Bag : Livre"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpBook",["Categorie"] = "Equipement",},
	["Bag : Cuir"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpCloth_Leather01",["Categorie"] = "Equipement",},
	["Bag : Général"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpFoodGeneric",["Categorie"] = "Equipement",},
	["Bag : Gemme"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpGems",["Categorie"] = "Equipement",},
	["Bag : Herbe"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpHerb",["Categorie"] = "Equipement",},
	["Bag : Chaine Grande"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpLargeChain",["Categorie"] = "Equipement",},
	["Bag : Meat"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpMeat",["Categorie"] = "Equipement",},
	["Bag : Metal Grand"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpMetalLArge",["Categorie"] = "Equipement",},
	["Bag : Metal Petit"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpMetalSmall",["Categorie"] = "Equipement",},
	["Bag : Parchemin"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpParchment_Paper",["Categorie"] = "Equipement",},
	["Bag : Anneau"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpRing",["Categorie"] = "Equipement",},
	["Bag : Pierre"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpRocks_Ore01",["Categorie"] = "Equipement",},
	["Bag : Chaine Petite"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpSmallChain",["Categorie"] = "Equipement",},
	["Bag : Baguette"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpWand",["Categorie"] = "Equipement",},
	["Bag : Liquide"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpWater_Liquid01",["Categorie"] = "Equipement",},
	["Bag : Bois Grand"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpWoodLarge",["Categorie"] = "Equipement",},
	["Bag : Bois Petit"] = {["Url"] = "Sound\\Interface\\PickUp\\PickUpWoodSmall",["Categorie"] = "Equipement",},
	["Bag off : Sac"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownBag",["Categorie"] = "Equipement",},
	["Bag off : Livre"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownBook",["Categorie"] = "Equipement",},
	["Bag off : Cuir"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownCloth_Leather01",["Categorie"] = "Equipement",},
	["Bag off : Général"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownFoodGeneric",["Categorie"] = "Equipement",},
	["Bag off : Gemme"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownGems",["Categorie"] = "Equipement",},
	["Bag off : Herbe"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownHerb",["Categorie"] = "Equipement",},
	["Bag off : Chaine Grande"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownLArgeChain",["Categorie"] = "Equipement",},
	["Bag off : Meat"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownMeat",["Categorie"] = "Equipement",},
	["Bag off : Metal Grand"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownLArgeMEtal",["Categorie"] = "Equipement",},
	["Bag off : Metal Petit"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownSmallMEtal",["Categorie"] = "Equipement",},
	["Bag off : Parchemin"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownParchment_Paper",["Categorie"] = "Equipement",},
	["Bag off : Anneau"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownRing",["Categorie"] = "Equipement",},
	["Bag off : Pierre"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownRocks_Ore01",["Categorie"] = "Equipement",},
	["Bag off : Chaine Petite"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownSmallChain",["Categorie"] = "Equipement",},
	["Bag off : Baguette"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownWand",["Categorie"] = "Equipement",},
	["Bag off : Liquide"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownWater_Liquid01",["Categorie"] = "Equipement",},
	["Bag off : Bois Grand"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownWoodLarge",["Categorie"] = "Equipement",},
	["Bag off : Bois Petit"] = {["Url"] = "Sound\\Interface\\PickUp\\PutDownWoodSmall",["Categorie"] = "Equipement",},
	["Gold 1"] = {["Url"] = "Sound\\Interface\\iMoneyDialogOpen",["Categorie"] = "Equipement",},
	["Gold 2"] = {["Url"] = "Sound\\Interface\\iMoneyDialogClose",["Categorie"] = "Equipement",},
	["Gold 3"] = {["Url"] = "Sound\\Interface\\LootCoinLarge",["Categorie"] = "Equipement",},
	["Gold 4"] = {["Url"] = "Sound\\Interface\\LootCoinSmall",["Categorie"] = "Equipement",},
	["Bag : Trousseau de Clés"] = {["Url"] = "Sound\\Interface\\KeyRingOpen",["Categorie"] = "Equipement",},
	["Bag off : Trousseau de Clés"] = {["Url"] = "Sound\\Interface\\KeyRingClose",["Categorie"] = "Equipement",},
	["Action : Écrire 1"] = {["Url"] = "Sound\\Interface\\WriteQuestA",["Categorie"] = "Livres",},
	["Action : Écrire 2"] = {["Url"] = "Sound\\Interface\\WriteQuestB",["Categorie"] = "Livres",},
	["Action : Écrire 3"] = {["Url"] = "Sound\\Interface\\WriteQuestC",["Categorie"] = "Livres",},
	["Papier 1"] = {["Url"] = "Sound\\Interface\\AchievementMenuClose",["Categorie"] = "Livres",},
	["Papier 2"] = {["Url"] = "Sound\\Interface\\AchievementMenuOpen",["Categorie"] = "Livres",},
	["Action : Ouvrir Livre"] = {["Url"] = "Sound\\Interface\\iAbilitiesOpenA",["Categorie"] = "Livres",},
	["Action : Fermer Livre"] = {["Url"] = "Sound\\Interface\\iAbilitiesCloseA",["Categorie"] = "Livres",},
	["Action : Tourner Page 1"] = {["Url"] = "Sound\\Interface\\iAbilitiesTurnPageA",["Categorie"] = "Livres",},
	["Action : Tourner Page 2"] = {["Url"] = "Sound\\Interface\\iAbilitiesTurnPageB",["Categorie"] = "Livres",},
	["Action : Tourner Page 3"] = {["Url"] = "Sound\\Interface\\iAbilitiesTurnPageC",["Categorie"] = "Livres",},
	["Action : Tourner Page 4"] = {["Url"] = "Sound\\Interface\\iQuestLogCloseA",["Categorie"] = "Livres",},
	["Action : Tourner Page 5"] = {["Url"] = "Sound\\Interface\\iQuestLogOpenA",["Categorie"] = "Livres",},
	["Murloc : Blblblbl 1"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAggroA",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 2"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAggroB",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 3"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAggroC",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 4"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAggroOld",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 5"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAttackA",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 6"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAttackB",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 7"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocAttackC",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 8"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocDeath2a",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 9"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocFidget2a",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 10"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocFidget2b",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 11"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocFidget3a",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 12"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocPreAggroA",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 13"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocWoundA",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 14"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocWoundB",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 15"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocWoundC",["Categorie"] = "Murloc",},
	["Murloc : Blblblbl 16"] = {["Url"] = "Sound\\Creature\\Murloc\\mMurlocWoundCriticalA",["Categorie"] = "Murloc",},
	["Bébé Murloc : Blblblbl 1"] = {["Url"] = "Sound\\Creature\\BabyMurloc\\BabyMurlocA",["Categorie"] = "Murloc",},
	["Bébé Murloc : Blblblbl 2"] = {["Url"] = "Sound\\Creature\\BabyMurloc\\BabyMurlocB",["Categorie"] = "Murloc",},
	["Bébé Murloc : Blblblbl 3"] = {["Url"] = "Sound\\Creature\\BabyMurloc\\BabyMurlocC",["Categorie"] = "Murloc",},
	["Bébé Murloc : Blblblbl 4"] = {["Url"] = "Sound\\Creature\\BabyMurloc\\BabyMurlocDance",["Categorie"] = "Murloc",},
	["Action : Gifler 1"] = {["Url"] = "Sound\\Character\\EmoteClap1",["Categorie"] = "Social",},
	["Action : Gifler 2"] = {["Url"] = "Sound\\Character\\EmoteClap2",["Categorie"] = "Social",},
	["Action : Gifler 3"] = {["Url"] = "Sound\\Character\\EmoteClap3",["Categorie"] = "Social",},
	["Action : Gifler 4"] = {["Url"] = "Sound\\Character\\EmoteClap4",["Categorie"] = "Social",},
	["Action : Gifler 5"] = {["Url"] = "Sound\\Character\\EmoteClap5",["Categorie"] = "Social",},
	["Action : Gifler 6"] = {["Url"] = "Sound\\Character\\EmoteClap6",["Categorie"] = "Social",},
	["Action : Gifler 7"] = {["Url"] = "Sound\\Character\\EmoteClap7",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 1"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle01",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 2"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle02",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 3"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle03",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 4"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle04",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 5"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle05",["Categorie"] = "Social",},
	["Action : Siffler (Ennui) 6"] = {["Url"] = "Sound\\Character\\EmoteBoredWhistle06",["Categorie"] = "Social",},
	["Action : Siffler (Drague) 1"] = {["Url"] = "Sound\\Character\\EmoteCatCallWhistle01",["Categorie"] = "Social",},
	["Action : Siffler (Drague) 2"] = {["Url"] = "Sound\\Character\\EmoteCatCallWhistle02",["Categorie"] = "Social",},
	["Action : Siffler (Drague) 3"] = {["Url"] = "Sound\\Character\\EmoteCatCallWhistle03",["Categorie"] = "Social",},
	["Action : Siffler (Drague) 4"] = {["Url"] = "Sound\\Character\\EmoteCatCallWhistle04",["Categorie"] = "Social",},
	["Action : Siffler (Drague) 5"] = {["Url"] = "Sound\\Character\\EmoteCatCallWhistle05",["Categorie"] = "Social",},
	["Action : Siffler (Familier)"] = {["Url"] = "Sound\\Spells\\PetCall",["Categorie"] = "Social",},
	["Action : Rire Femme 1"] = {["Url"] = "Sound\\Character\\BloodElf\\BloodElfFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 2"] = {["Url"] = "Sound\\Character\\Draenei\\DraeneiFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 3"] = {["Url"] = "Sound\\Character\\Dwarf\\DwarfFemale\\DwarfFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 4"] = {["Url"] = "Sound\\Character\\Gnome\\GnomeFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 5"] = {["Url"] = "Sound\\Character\\Human\\Female\\HumanFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 6"] = {["Url"] = "Sound\\Character\\NightElf\\NightElfFemale\\NightElfFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 7"] = {["Url"] = "Sound\\Character\\Orc\\Female\\OrcFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 8"] = {["Url"] = "Sound\\Character\\Scourge\\ScourgeFemale\\UndeadFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 9"] = {["Url"] = "Sound\\Character\\Tauren\\Female\\TaurenFemaleLaugh01",["Categorie"] = "Social",},
	["Action : Rire Femme 10"] = {["Url"] = "Sound\\Character\\Troll\\TrollFemaleLaugh01",["Categorie"] = "Social",},
	["Rifle : Tir 1"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunFire01",["Categorie"] = "Weapons",},
	["Rifle : Tir 2"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunFire02",["Categorie"] = "Weapons",},
	["Rifle : Tir 3"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunFire03",["Categorie"] = "Weapons",},
	["Rifle : Recharge 1"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunLoad01",["Categorie"] = "Weapons",},
	["Rifle : Recharge 2"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunLoad02",["Categorie"] = "Weapons",},
	["Rifle : Recharge 3"] = {["Url"] = "Sound\\Item\\Weapons\\Gun\\GunLoad03",["Categorie"] = "Weapons",},
	["Whip : Attaque 1"] = {["Url"] = "Sound\\Item\\Weapons\\Whip\\BullWhipHit1",["Categorie"] = "Weapons",},
	["Whip : Attaque 2"] = {["Url"] = "Sound\\Item\\Weapons\\Whip\\BullWhipHit2",["Categorie"] = "Weapons",},
	["Whip : Attaque 3"] = {["Url"] = "Sound\\Item\\Weapons\\Whip\\BullWhipHit3",["Categorie"] = "Weapons",},
	["Glass : Brisé 1"] = {["Url"] = "Sound\\Spells\\GlassBreaking1",["Categorie"] = "Items",},
	["Glass : Brisé 2"] = {["Url"] = "Sound\\Spells\\GlassBreaking2",["Categorie"] = "Items",},
	["Glass : Brisé 3"] = {["Url"] = "Sound\\Spells\\GlassBreaking3",["Categorie"] = "Items",},
	["Glass : Enflamme 1"] = {["Url"] = "Sound\\Spells\\MoltovCocktailImpactA",["Categorie"] = "Items",},
	["Glass : Enflamme 2"] = {["Url"] = "Sound\\Spells\\MoltovCocktailImpactB",["Categorie"] = "Items",},
	["Glass : Enflamme 3"] = {["Url"] = "Sound\\Spells\\MoltovCocktailImpactC",["Categorie"] = "Items",},
	["Action : Cuisiner 1"] = {["Url"] = "Sound\\Spells\\Tradeskills\\CookingPrepareA",["Categorie"] = "Cuisine",},
	["Action : Cuisiner 2"] = {["Url"] = "Sound\\Spells\\Tradeskills\\CookingPrepareB",["Categorie"] = "Cuisine",},
	["Action : Cuisiner 3"] = {["Url"] = "Sound\\Spells\\Tradeskills\\CookingPrepareC",["Categorie"] = "Cuisine",},
	["Action : Cuisiner 4"] = {["Url"] = "Sound\\Spells\\Tradeskills\\CookingCompleteA",["Categorie"] = "Cuisine",},
	["Meat 1"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh1",["Categorie"] = "Cuisine",},
	["Meat 2"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh2",["Categorie"] = "Cuisine",},
	["Meat 3"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh3",["Categorie"] = "Cuisine",},
	["Meat 4"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh4",["Categorie"] = "Cuisine",},
	["Meat 5"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh5",["Categorie"] = "Cuisine",},
	["Meat 6"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh6",["Categorie"] = "Cuisine",},
	["Meat 7"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh7",["Categorie"] = "Cuisine",},
	["Meat 8"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh8",["Categorie"] = "Cuisine",},
	["Meat 9"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh9",["Categorie"] = "Cuisine",},
	["Meat 10"] = {["Url"] = "Sound\\Spells\\WolfEatFlesh10",["Categorie"] = "Cuisine",},
	["Mecha : Gaz 1"] = {["Url"] = "Sound\\Vehicles\\MotorcycleVehicle\\MotorcycleVehicleJumpStart1",["Categorie"] = "Mount",},
	["Mecha : Gaz 2"] = {["Url"] = "Sound\\Vehicles\\MotorcycleVehicle\\MotorcycleVehicleJumpStart2",["Categorie"] = "Mount",},
	["Mecha : Gaz 3"] = {["Url"] = "Sound\\Vehicles\\MotorcycleVehicle\\MotorcycleVehicleJumpStart3",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 1"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Ground_GearShift_1",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 2"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Ground_GearShift_2",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 3"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Ground_GearShift_3",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 4"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Ground_GearShift_4",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 5"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Ground_GearShift_5",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 6"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_1",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 7"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_2",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 8"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_3",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 9"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_4",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 10"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_5",["Categorie"] = "Mount",},
	["Mecha : Levier de vitesse 11"] = {["Url"] = "Sound\\Vehicles\\Vehicle_Airplane_GearShift_6",["Categorie"] = "Mount",},
	["Mecha : Monter"] = {["Url"] = "Sound\\Vehicles\\VehicleMount",["Categorie"] = "Mount",},
	["Mecha : Descendre"] = {["Url"] = "Sound\\Vehicles\\VehicleDismount",["Categorie"] = "Mount",},
	["Animal : Monter"] = {["Url"] = "Sound\\Vehicles\\VehicleMount_Organic",["Categorie"] = "Mount",},
	["Animal : Descendre"] = {["Url"] = "Sound\\Vehicles\\VehicleDismount_Organic",["Categorie"] = "Mount",},
	["Panic : Homme 1"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream1_01",["Categorie"] = "Cris",},
	["Panic : Homme 2"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream1_02",["Categorie"] = "Cris",},
	["Panic : Homme 3"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream1_03",["Categorie"] = "Cris",},
	["Panic : Homme 4"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream1_04",["Categorie"] = "Cris",},
	["Panic : Homme 5"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_01",["Categorie"] = "Cris",},
	["Panic : Homme 6"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_02",["Categorie"] = "Cris",},
	["Panic : Homme 7"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_03",["Categorie"] = "Cris",},
	["Panic : Homme 8"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_04",["Categorie"] = "Cris",},
	["Panic : Homme 9"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_05",["Categorie"] = "Cris",},
	["Panic : Homme 10"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_06",["Categorie"] = "Cris",},
	["Panic : Homme 11"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_07",["Categorie"] = "Cris",},
	["Panic : Homme 12"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_08",["Categorie"] = "Cris",},
	["Panic : Homme 13"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_09",["Categorie"] = "Cris",},
	["Panic : Homme 14"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream2_10",["Categorie"] = "Cris",},
	["Panic : Homme 15"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_01",["Categorie"] = "Cris",},
	["Panic : Homme 16"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_02",["Categorie"] = "Cris",},
	["Panic : Homme 17"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_03",["Categorie"] = "Cris",},
	["Panic : Homme 18"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_04",["Categorie"] = "Cris",},
	["Panic : Homme 19"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_05",["Categorie"] = "Cris",},
	["Panic : Homme 20"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_06",["Categorie"] = "Cris",},
	["Panic : Homme 21"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_07",["Categorie"] = "Cris",},
	["Panic : Homme 22"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_08",["Categorie"] = "Cris",},
	["Panic : Homme 23"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_09",["Categorie"] = "Cris",},
	["Panic : Homme 24"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream3_10",["Categorie"] = "Cris",},
	["Panic : Homme 25"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_01",["Categorie"] = "Cris",},
	["Panic : Homme 26"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_02",["Categorie"] = "Cris",},
	["Panic : Homme 27"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_03",["Categorie"] = "Cris",},
	["Panic : Homme 28"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_04",["Categorie"] = "Cris",},
	["Panic : Homme 29"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_05",["Categorie"] = "Cris",},
	["Panic : Homme 30"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_06",["Categorie"] = "Cris",},
	["Panic : Homme 31"] = {["Url"] = "Sound\\Events\\EbonHold_ManScream4_07",["Categorie"] = "Cris",},
	["Cri Lointain : Nain"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsDwarfMale",["Categorie"] = "Cris",},
	["Cri Lointain : Naine"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsDwarfFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Gnome"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsGnomeMale",["Categorie"] = "Cris",},
	["Cri Lointain : Gnomette"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsGnomeFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Humain"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsHumanMale",["Categorie"] = "Cris",},
	["Cri Lointain : Humaine"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsHumanFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Elfe de la Nuit (M)"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsNightElfMale",["Categorie"] = "Cris",},
	["Cri Lointain : Elfe de la Nuit (F)"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsNightElfFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Orc"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsOrcMale",["Categorie"] = "Cris",},
	["Cri Lointain : Orque"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsOrcFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Tauren"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsTaurenMale",["Categorie"] = "Cris",},
	["Cri Lointain : Taurène"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsTaurenFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Troll"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsTrollMale",["Categorie"] = "Cris",},
	["Cri Lointain : Trolle"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsTrollFemale",["Categorie"] = "Cris",},
	["Cri Lointain : Réprouvé"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsUndeadMale",["Categorie"] = "Cris",},
	["Cri Lointain : Réprouvée"] = {["Url"] = "Sound\\Character\\PlayerRoars\\CharacterRoarsUndeadFemale",["Categorie"] = "Cris",},
	["Dragon : Aggro"] = {["Url"] = "Sound\\Creature\\Dragons\\DragonAggro",["Categorie"] = "Dragon",},
	["Dragon : Attaque 1"] = {["Url"] = "Sound\\Creature\\Dragons\\DragonAttackA",["Categorie"] = "Dragon",},
	["Dragon : Attaque 2"] = {["Url"] = "Sound\\Creature\\Dragons\\DragonAttackB",["Categorie"] = "Dragon",},
	["Dragon : Attaque 3"] = {["Url"] = "Sound\\Creature\\Dragons\\DragonAttackC",["Categorie"] = "Dragon",},
	["Dragon : Grognement"] = {["Url"] = "Sound\\Creature\\Dragons\\DragonPreAggro",["Categorie"] = "Dragon",},
	["Dragon : Battement d'aile 1"] = {["Url"] = "Sound\\Creature\\Dragons\\HugeWingFlap1",["Categorie"] = "Dragon",},
	["Dragon : Battement d'aile 2"] = {["Url"] = "Sound\\Creature\\Dragons\\HugeWingFlap2",["Categorie"] = "Dragon",},
	["Dragonnet : Aggro 1"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpAggroA",["Categorie"] = "Dragon",},
	["Dragonnet : Aggro 2"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpAggroB",["Categorie"] = "Dragon",},
	["Dragonnet : Attaque 1"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpAttackA",["Categorie"] = "Dragon",},
	["Dragonnet : Attaque 2"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpAttackB",["Categorie"] = "Dragon",},
	["Dragonnet : Attaque 3"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpAttackC",["Categorie"] = "Dragon",},
	["Dragonnet : Crainte 1"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpRunFidgetA",["Categorie"] = "Dragon",},
	["Dragonnet : Crainte 2"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpRunFidgetB",["Categorie"] = "Dragon",},
	["Dragonnet : Crainte 3"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpRunFidgetC",["Categorie"] = "Dragon",},
	["Dragonnet : Blessé 1"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWoundA",["Categorie"] = "Dragon",},
	["Dragonnet : Blessé 2"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWoundB",["Categorie"] = "Dragon",},
	["Dragonnet : Blessé 3"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWoundC",["Categorie"] = "Dragon",},
	["Dragonnet : Couinement"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWalkFidgetA",["Categorie"] = "Dragon",},
	["Dragonnet : Battement d'aile 1"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWingFlapA",["Categorie"] = "Dragon",},
	["Dragonnet : Battement d'aile 2"] = {["Url"] = "Sound\\Creature\\DragonWhelp\\mDragonWhelpWingFlapB",["Categorie"] = "Dragon",},
	["Drake : Aggro"] = {["Url"] = "Sound\\Creature\\Drake\\DrakeAggro",["Categorie"] = "Dragon",},
	["Drake : Attaque 1"] = {["Url"] = "Sound\\Creature\\Drake\\DrakeAttackA",["Categorie"] = "Dragon",},
	["Drake : Attaque 2"] = {["Url"] = "Sound\\Creature\\Drake\\DrakeAttackB",["Categorie"] = "Dragon",},
	["Drake : Attaque 3"] = {["Url"] = "Sound\\Creature\\Drake\\DrakeAttackC",["Categorie"] = "Dragon",},
	["Drake : Grognement"] = {["Url"] = "Sound\\Creature\\Drake\\DrakePreAggro",["Categorie"] = "Dragon",},
	["Drake du Néant : Cri 1"] = {["Url"] = "Sound\\Creature\\NetherDrake\\NetherDrakeA",["Categorie"] = "Dragon",},
	["Drake du Néant : Cri 2"] = {["Url"] = "Sound\\Creature\\NetherDrake\\NetherDrakeB",["Categorie"] = "Dragon",},
	["Cerf : Brâme 1"] = {["Url"] = "Sound\\Creature\\Deer\\DeerDeathA",["Categorie"] = "Animaux en Vrac",},
	["Cerf : Brâme 2"] = {["Url"] = "Sound\\Creature\\Deer\\DeerWoundA",["Categorie"] = "Animaux en Vrac",},
	["Poulet : Cot Cot 1"] = {["Url"] = "Sound\\Creature\\Chicken\\ChickenDeathA",["Categorie"] = "Animaux en Vrac",},
	["Poulet : Cot Cot 2"] = {["Url"] = "Sound\\Creature\\Chicken\\ChickenWoundA",["Categorie"] = "Animaux en Vrac",},
	["Poulet : Cot Cot 3"] = {["Url"] = "Sound\\Creature\\ChickenMount\\ChickenMountWound1",["Categorie"] = "Animaux en Vrac",},
	["Poulet : Cot Cot 4"] = {["Url"] = "Sound\\Creature\\ChickenMount\\ChickenMountWound2",["Categorie"] = "Animaux en Vrac",},
	["Poulet : Cot Cot 5"] = {["Url"] = "Sound\\Creature\\ChickenMount\\ChickenMountSpecialMount",["Categorie"] = "Animaux en Vrac",},
	["Bébé Crocodile : Couinement 1"] = {["Url"] = "Sound\\Creature\\BabyCrocodile\\BabyCrocodileClick1",["Categorie"] = "Animaux en Vrac",},
	["Bébé Crocodile : Couinement 2"] = {["Url"] = "Sound\\Creature\\BabyCrocodile\\BabyCrocodileClick2",["Categorie"] = "Animaux en Vrac",},
	["Bébé Crocodile : Couinement 3"] = {["Url"] = "Sound\\Creature\\BabyCrocodile\\BabyCrocodileClick3",["Categorie"] = "Animaux en Vrac",},
	["Bébé Crocodile : Couinement 4"] = {["Url"] = "Sound\\Creature\\BabyCrocodile\\BabyCrocodileClick4",["Categorie"] = "Animaux en Vrac",},
	["Bébé Crocodile : Couinement 5"] = {["Url"] = "Sound\\Creature\\BabyCrocodile\\BabyCrocodileClick5",["Categorie"] = "Animaux en Vrac",},
	["Vache : Meuh 1"] = {["Url"] = "Sound\\Creature\\Cow\\CowDeath",["Categorie"] = "Animaux en Vrac",},
	["Vache : Meuh 2"] = {["Url"] = "Sound\\Creature\\Cow\\CowWound",["Categorie"] = "Animaux en Vrac",},
	["Bébé Elekk : Couinement 1"] = {["Url"] = "Sound\\Creature\\ElekkPet\\ElekkClick1",["Categorie"] = "Animaux en Vrac",},
	["Bébé Elekk : Couinement 2"] = {["Url"] = "Sound\\Creature\\ElekkPet\\ElekkClick2",["Categorie"] = "Animaux en Vrac",},
	["Bébé Elekk : Couinement 3"] = {["Url"] = "Sound\\Creature\\ElekkPet\\ElekkClick3",["Categorie"] = "Animaux en Vrac",},
	["Fire Follet : Bruit 1"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispPissed1",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 2"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispPissed2",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 3"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispPissed3",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 4"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispYes1",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 5"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispYes2",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 6"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispYes3",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 7"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispWhat1",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 8"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispWhat2",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 9"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispWhat3",["Categorie"] = "Fire Follet",},
	["Fire Follet : Bruit 10"] = {["Url"] = "Sound\\Event Sounds\\Wisp\\WispReady1",["Categorie"] = "Fire Follet",},
	["Plouf : Petit"] = {["Url"] = "Sound\\Effects\\DeathImpacts\\InWater\\mDeathImpactSmallWaterA",["Categorie"] = "Eau",},
	["Plouf : Moyen"] = {["Url"] = "Sound\\Effects\\DeathImpacts\\InWater\\mDeathImpactMediumWaterA",["Categorie"] = "Eau",},
	["Plouf : Grand"] = {["Url"] = "Sound\\Effects\\DeathImpacts\\InWater\\mDeathImpactGiantWaterA",["Categorie"] = "Eau",},
	["Plouf : Géant"] = {["Url"] = "Sound\\Effects\\DeathImpacts\\InWater\\mDeathImpactColossalWaterA",["Categorie"] = "Eau",},
	["Horse : Hénnissement 1"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseAggroA",["Categorie"] = "Horse",},
	["Horse : Hénnissement 2"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseAttackA",["Categorie"] = "Horse",},
	["Horse : Hénnissement 3"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseDeathA",["Categorie"] = "Horse",},
	["Horse : Hénnissement 4"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseStand3A",["Categorie"] = "Horse",},
	["Horse : Hénnissement 5"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseWoundA",["Categorie"] = "Horse",},
	["Horse : Hénnissement 6"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseWoundB",["Categorie"] = "Horse",},
	["Horse : Hénnissement 7"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseWoundC",["Categorie"] = "Horse",},
	["Horse : Hénnissement 8"] = {["Url"] = "Sound\\Creature\\Horse\\mHorseWoundCriticalA",["Categorie"] = "Horse",},
	["ERP : Femme Naine 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Naine 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Naine 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Naine 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Naine 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Naine 6"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfFemaleFinal\\DwarfFemaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Nain 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Nain 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Nain 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Nain 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Nain 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Nain 6"] = {["Url"] = "Sound\\Character\\PlayerExertions\\DwarfMaleFinal\\DwarfMaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Femme Gnome 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeFemaleFinal\\GnomeFemaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Gnome 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeFemaleFinal\\GnomeFemaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Gnome 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeFemaleFinal\\GnomeFemaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Gnome 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeFemaleFinal\\GnomeFemaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Gnome 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeFemaleFinal\\GnomeFemaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Gnome 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeMaleFinal\\GnomeMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Gnome 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeMaleFinal\\GnomeMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Gnome 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeMaleFinal\\GnomeMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Gnome 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeMaleFinal\\GnomeMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Gnome 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\GnomeMaleFinal\\GnomeMaleMainWoundCrit",["Categorie"] = "ERP",},
	["ERP : Femme Humain 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanFemaleFinal\\HumanFeamleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Humain 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanFemaleFinal\\HumanFeamleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Humain 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanFemaleFinal\\HumanFeamleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Humain 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanFemaleFinal\\HumanFeamleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Humain 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanFemaleFinal\\HumanFeamleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Humain 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanMaleFinal\\HumanMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Humain 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanMaleFinal\\HumanMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Humain 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanMaleFinal\\HumanMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Humain 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanMaleFinal\\HumanMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Humain 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\HumanMaleFinal\\HumanMaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de la Nuit 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfFemaleFinal\\NightElfFemaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de la Nuit 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfFemaleFinal\\NightElfFemaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de la Nuit 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfFemaleFinal\\NightElfFemaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de la Nuit 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfFemaleFinal\\NightElfFemaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de la Nuit 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfFemaleFinal\\NightElfFemaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de la Nuit 6"] = {["Url"] = "Sound\\Character\\PlayerExertions\\NightElfMaleFinal\\NightElfMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Orc 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Orc 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Orc 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Orc 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Orc 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Femme Orc 6"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcFemaleFinal\\OrcFemaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Orc 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcMale\\OrcMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Orc 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcMale\\OrcMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Orc 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcMale\\OrcMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Orc 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcMale\\OrcMaleMainWoundCrit",["Categorie"] = "ERP",},
	["ERP : Homme Orc 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\OrcMale\\OrcMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Tauren 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenFemaleFinal\\TaurenFemaleFinalWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Tauren 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenFemaleFinal\\TaurenFemaleFinalWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Tauren 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenFemaleFinal\\TaurenFemaleFinalWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Tauren 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenFemaleFinal\\TaurenFemaleFinalWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Tauren 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenMaleFinal\\TaurenMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Tauren 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenMaleFinal\\TaurenMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Tauren 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenMaleFinal\\TaurenMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Tauren 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenMaleFinal\\TaurenMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Tauren 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TaurenMaleFinal\\TaurenMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Troll 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollFemaleFinal\\TrollFemalMainWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Troll 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollFemaleFinal\\TrollFemalMainWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Troll 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollFemaleFinal\\TrollFemalMainWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Troll 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollFemaleFinal\\TrollFemalMainWoundCrit",["Categorie"] = "ERP",},
	["ERP : Homme Troll 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Troll 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Troll 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Troll 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Troll 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Troll 6"] = {["Url"] = "Sound\\Character\\PlayerExertions\\TrollMaleFinal\\TrollMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Réprouvé 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadFemaleFinal\\UndeadFemaleFinalWound",["Categorie"] = "ERP",},
	["ERP : Femme Réprouvé 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadFemaleFinal\\UndeadFemaleFinalWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Réprouvé 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadFemaleFinal\\UndeadFemaleFinalWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Réprouvé 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadFemaleFinal\\UndeadFemaleFinalWoundCriatA",["Categorie"] = "ERP",},
	["ERP : Homme Réprouvé 1"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadMaleFinal\\UndeadMaleMainWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Réprouvé 2"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadMaleFinal\\UndeadMaleMainWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Réprouvé 3"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadMaleFinal\\UndeadMaleMainWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Réprouvé 4"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadMaleFinal\\UndeadMaleMainWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Réprouvé 5"] = {["Url"] = "Sound\\Character\\PlayerExertions\\UndeadMaleFinal\\UndeadMaleMainWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 1"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCDeath",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 2"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCCritA",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 3"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCCritB",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 4"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCCritC",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 5"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWound",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 6"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 7"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 8"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 9"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWoundE",["Categorie"] = "ERP",},
	["ERP : Femme Elfe de Sang 10"] = {["Url"] = "Sound\\Character\\BloodElfFemalePC\\BloodElfFemalePCWoundF",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 1"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCDeath2",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 2"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCDeath",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 3"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 4"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 5"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundCritC",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 6"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 7"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 8"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 9"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 10"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundE",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 11"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundF",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 12"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundG",["Categorie"] = "ERP",},
	["ERP : Homme Elfe de Sang 13"] = {["Url"] = "Sound\\Character\\BloodElfMalePC\\BloodElfMalePCWoundH",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 1"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCDeath",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 2"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundA",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 3"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundB",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 4"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundC",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 5"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundCritA",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 6"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundCritB",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 7"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundCritC",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 8"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundD",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 9"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundE",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 10"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundF",["Categorie"] = "ERP",},
	["ERP : Femme Draenei 11"] = {["Url"] = "Sound\\Character\\DraeneiFemalePC\\DraeneiFemalePCWoundG",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 1"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundI",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 2"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCDeath",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 3"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundCritA",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 4"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundCritB",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 5"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundCritC",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 6"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundA",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 7"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundB",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 8"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundC",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 9"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundD",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 10"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundE",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 11"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundF",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 12"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundG",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 13"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundH",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 14"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundCritD",["Categorie"] = "ERP",},
	["ERP : Homme Draenei 15"] = {["Url"] = "Sound\\Character\\DraeneiMalePC\\DraeneiMalePCWoundCritE",["Categorie"] = "ERP",},
	["Druid : Spell 1"] = {["Url"] = "Sound\\Spells\\Druid_Berserk",["Categorie"] = "Druid",},
	["Druid : Spell 2"] = {["Url"] = "Sound\\Spells\\Druid_Brambles1",["Categorie"] = "Druid",},
	["Druid : Spell 3"] = {["Url"] = "Sound\\Spells\\Druid_Brambles2",["Categorie"] = "Druid",},
	["Druid : Spell 4"] = {["Url"] = "Sound\\Spells\\Druid_Brambles3",["Categorie"] = "Druid",},
	["Druid : Spell 5"] = {["Url"] = "Sound\\Spells\\Druid_Brambles1",["Categorie"] = "Druid",},
	["Druid : Spell 6"] = {["Url"] = "Sound\\Spells\\Druid_Eclipse",["Categorie"] = "Druid",},
	["Druid : Spell 7"] = {["Url"] = "Sound\\Spells\\Druid_Flourish",["Categorie"] = "Druid",},
	["Druid : Spell 8"] = {["Url"] = "Sound\\Spells\\Druid_Nourish",["Categorie"] = "Druid",},
	["Druid : Spell 9"] = {["Url"] = "Sound\\Spells\\Druid_Pounce",["Categorie"] = "Druid",},
	["Druid : Spell 10"] = {["Url"] = "Sound\\Spells\\Druid_Replenish",["Categorie"] = "Druid",},
	["Druid : Spell 11"] = {["Url"] = "Sound\\Spells\\Druid_SavageRoar_Impact01",["Categorie"] = "Druid",},
	["Druid : Spell 12"] = {["Url"] = "Sound\\Spells\\Druid_SavageRoar_Impact02",["Categorie"] = "Druid",},
	["Druid : Spell 13"] = {["Url"] = "Sound\\Spells\\Druid_SavageRoar_Impact03",["Categorie"] = "Druid",},
	["Druid : Spell 14"] = {["Url"] = "Sound\\Spells\\Druid_StarfallMissile1",["Categorie"] = "Druid",},
	["Druid : Spell 15"] = {["Url"] = "Sound\\Spells\\Druid_StarfallMissile2",["Categorie"] = "Druid",},
	["Druid : Spell 16"] = {["Url"] = "Sound\\Spells\\Druid_StarfallMissile3",["Categorie"] = "Druid",},
	["Druid : Spell 17"] = {["Url"] = "Sound\\Spells\\Druid_Survival_Istincts",["Categorie"] = "Druid",},
	["Druid : Morph"] = {["Url"] = "Sound\\Spells\\DruidMorph_Impact_Base",["Categorie"] = "Druid",},
	["Druid : Tranquilité"] = {["Url"] = "Sound\\Spells\\Tranquility",["Categorie"] = "Druid",},
	["Arbre Ancien : Craquement 1"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientAttack1",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 2"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientAttack2",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 3"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientAttack3",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 4"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientDeath1",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 5"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientStandFidget1",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 6"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientStandFidget2",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 7"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientStandFidget3",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 8"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientWound1",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 9"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientWound2",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 10"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientWound3",["Categorie"] = "Arbre",},
	["Arbre Ancien : Craquement 11"] = {["Url"] = "Sound\\Creature\\AncientProtector\\mAncientWoundCritical1",["Categorie"] = "Arbre",},
	["Boum : Bâtiment 1"] = {["Url"] = "Sound\\Doodad\\WG_Bridge02_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 2"] = {["Url"] = "Sound\\Doodad\\WG_Bridge02_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 3"] = {["Url"] = "Sound\\Doodad\\WG_Gate01_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 4"] = {["Url"] = "Sound\\Doodad\\WG_Gate01_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 5"] = {["Url"] = "Sound\\Doodad\\WG_Keep_Door01_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 6"] = {["Url"] = "Sound\\Doodad\\WG_Keep_Door01_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 7"] = {["Url"] = "Sound\\Doodad\\WG_Siege01_FX1_Custom0",["Categorie"] = "Boum",},
	["Boum : Bâtiment 8"] = {["Url"] = "Sound\\Doodad\\WG_Tower01_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 9"] = {["Url"] = "Sound\\Doodad\\WG_Tower01_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 10"] = {["Url"] = "Sound\\Doodad\\WG_Wall01_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 11"] = {["Url"] = "Sound\\Doodad\\WG_Wall01_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 12"] = {["Url"] = "Sound\\Doodad\\WG_Wall02_FX1",["Categorie"] = "Boum",},
	["Boum : Bâtiment 13"] = {["Url"] = "Sound\\Doodad\\WG_Wall02_FX2",["Categorie"] = "Boum",},
	["Boum : Bâtiment 14"] = {["Url"] = "Sound\\Doodad\\WG_Tower01_FX2b_Custom0",["Categorie"] = "Boum",},
	["Boum : Tremblement de terre 1"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Debris",["Categorie"] = "Boum",},
	
	["Boum : Brol 1 Cassé 1"] = {["Url"] = "Sound\\Doodad\\G_BearTrapReverse_Destroy01",["Categorie"] = "Boum",},
	["Boum : Brol 1 Cassé 2"] = {["Url"] = "Sound\\Doodad\\G_BearTrapReverse_Destroy02",["Categorie"] = "Boum",},
	["Boum : Brol 1 Cassé 3"] = {["Url"] = "Sound\\Doodad\\G_BearTrapReverse_Destroy03",["Categorie"] = "Boum",},
	["Boum : Brol 1 Cassé 4"] = {["Url"] = "Sound\\Doodad\\G_BearTrapReverse_Destroy04",["Categorie"] = "Boum",},
	["Boum : Brol 1 Cassé 5"] = {["Url"] = "Sound\\Doodad\\G_BearTrapReverse_Destroy05",["Categorie"] = "Boum",},
	
	["Boum : Brol 2 Cassé 1"] = {["Url"] = "Sound\\Creature\\Cannon\\CannonWoundA",["Categorie"] = "Boum",},
	["Boum : Brol 2 Cassé 2"] = {["Url"] = "Sound\\Creature\\Cannon\\CannonWoundB",["Categorie"] = "Boum",},
	["Boum : Brol 2 Cassé 3"] = {["Url"] = "Sound\\Creature\\Cannon\\CannonWoundC",["Categorie"] = "Boum",},
	["Boum : Brol 2 Cassé 4"] = {["Url"] = "Sound\\Creature\\Cannon\\CannonDeath",["Categorie"] = "Boum",},
	
	["Corde : Grincement 1"] = {["Url"] = "Sound\\Doodad\\RopeCreak01",["Categorie"] = "Corde",},
	["Corde : Grincement 2"] = {["Url"] = "Sound\\Doodad\\RopeCreak02",["Categorie"] = "Corde",},
	["Corde : Grincement 3"] = {["Url"] = "Sound\\Doodad\\RopeCreak03",["Categorie"] = "Corde",},
	["Corde : Grincement 4"] = {["Url"] = "Sound\\Doodad\\RopeCreak04",["Categorie"] = "Corde",},
	["Corde : Grincement 5"] = {["Url"] = "Sound\\Doodad\\RopeCreak05",["Categorie"] = "Corde",},
	
	["Météorite : Impact 1"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion01",["Categorie"] = "Météorite",},
	["Météorite : Impact 2"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion02",["Categorie"] = "Météorite",},
	["Météorite : Impact 3"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion03",["Categorie"] = "Météorite",},
	["Météorite : Impact 4"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion04",["Categorie"] = "Météorite",},
	["Météorite : Impact 5"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion05",["Categorie"] = "Météorite",},
	["Météorite : Impact 6"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion06",["Categorie"] = "Météorite",},
	["Météorite : Impact 7"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion07",["Categorie"] = "Météorite",},
	["Météorite : Impact 8"] = {["Url"] = "Sound\\Doodad\\Hellfire_Raid_FX_Explosion08",["Categorie"] = "Météorite",},
	
	["Gobelin : Bidule 1"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Open01",["Categorie"] = "Technologie Gobeline",},
	["Gobelin : Bidule 2"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Open02",["Categorie"] = "Technologie Gobeline",},
	["Gobelin : Bidule 3"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Open03",["Categorie"] = "Technologie Gobeline",},
	["Gobelin : Bidule 4"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Open04",["Categorie"] = "Technologie Gobeline",},
	["Gobelin : Bidule 5"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Open05",["Categorie"] = "Technologie Gobeline",},
	["Gobelin : Fax"] = {["Url"] = "Sound\\Doodad\\Goblin_Lottery_Opened",["Categorie"] = "Technologie Gobeline",},
	
	["Fire : Explosion 1"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral1",["Categorie"] = "Fire d'Artifice",},
	["Fire : Explosion 2"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral2",["Categorie"] = "Fire d'Artifice",},
	["Fire : Explosion 3"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral3",["Categorie"] = "Fire d'Artifice",},
	["Fire : Explosion 4"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral4",["Categorie"] = "Fire d'Artifice",},
	["Fire : Explosion 5"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral5",["Categorie"] = "Fire d'Artifice",},
	["Fire : Explosion 6"] = {["Url"] = "Sound\\Doodad\\G_FireworkBoomGeneral6",["Categorie"] = "Fire d'Artifice",},
	
	["Fire : Lancement 1"] = {["Url"] = "Sound\\Doodad\\G_FireworkLauncher01Custom3",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 2"] = {["Url"] = "Sound\\Doodad\\G_FireworkLauncher02Custom0",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 3"] = {["Url"] = "Sound\\Doodad\\G_FireworkLauncher02Custom3",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 4"] = {["Url"] = "Sound\\Doodad\\G_FireworkTwirlySmall01Gold",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 5"] = {["Url"] = "Sound\\Doodad\\G_FlareAlliance_Spawn01",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 6"] = {["Url"] = "Sound\\Doodad\\G_FlareAlliance_Spawn02",["Categorie"] = "Fire d'Artifice",},
	["Fire : Lancement 7"] = {["Url"] = "Sound\\Doodad\\G_FlareAlliance_Spawn03",["Categorie"] = "Fire d'Artifice",},
	
	["Poêle : Coup 1"] = {["Url"] = "Sound\\Doodad\\UL_Forge_Iron_PressOneShot1",["Categorie"] = "Weapons",},
	["Poêle : Coup 2"] = {["Url"] = "Sound\\Doodad\\UL_Forge_Iron_PressOneShot2",["Categorie"] = "Weapons",},
	["Poêle : Coup 3"] = {["Url"] = "Sound\\Doodad\\UL_Forge_Iron_PressOneShot3",["Categorie"] = "Weapons",},
	["Poêle : Coup 4"] = {["Url"] = "Sound\\Doodad\\UL_Forge_Iron_PressOneShot4",["Categorie"] = "Weapons",},
	
	["Blague : Vent"] = {["Url"] = "Sound\\Doodad\\ZulAman_WindDoorClose",["Categorie"] = "Social",},
	["Taverne : Vomir 1"] = {["Url"] = "Sound\\Creature\\Oracle\\OracleAttackC",["Categorie"] = "Social",},
	["Taverne : Vomir 2"] = {["Url"] = "Sound\\Creature\\Oracle\\OracleAttackE",["Categorie"] = "Social",},
}

TRP_LISTE_SOUNDS_ICON = {
	["Cat"] = "Interface\\ICONS\\Ability_Hunter_CatLikeReflexes.blp",
	["Pig"] = "Interface\\ICONS\\Spell_Magic_PolymorphPig.blp",
	["Dog"] = "Interface\\ICONS\\Ability_Hunter_Pet_Wolf.blp",
	["Ambiance : Ice"] = "Interface\\ICONS\\Spell_Frost_FrostNova.blp",
	["Alchemy"] = "Interface\\ICONS\\INV_Alchemy_EndlessFlask_03.blp",
	["Cris"] = "Interface\\ICONS\\INV_Relics_TotemofRage.blp",
	["Barbier"] = "Interface\\ICONS\\INV_Misc_Comb_02.blp",
	["Mobilier"] = "Interface\\ICONS\\INV_Box_01.blp",
	["Equipement"] = "Interface\\ICONS\\INV_Misc_Bag_22.blp",
	["Livres"] = "Interface\\ICONS\\INV_Inscription_Tradeskill01.blp",
	["Murloc"] = "Interface\\ICONS\\INV_Misc_Head_Murloc_01.blp",
	["Social"] = "Interface\\ICONS\\Achievement_Reputation_06.blp",
	["Weapons"] = "Interface\\ICONS\\Spell_Holy_WeaponMastery.blp",
	["Items"] = "Interface\\ICONS\\INV_Misc_Gear_08.blp",
	["Cuisine"] = "Interface\\ICONS\\INV_Misc_Food_63.blp",
	["Mount"] = "Interface\\ICONS\\Ability_Mount_Charger.blp",
	["Dragon"] = "Interface\\ICONS\\INV_Misc_Head_Dragon_Blue.blp",
	["Animaux en Vrac"] = "Interface\\ICONS\\Spell_Magic_PolymorphChicken.blp",
	["Fire Follet"] = "Interface\\ICONS\\Spell_Shadow_MindTwisting.blp",
	["Eau"] = "Interface\\ICONS\\INV_Elemental_Primal_Water.blp",
	["Horse"] = "Interface\\ICONS\\Ability_Mount_NightmareHorse.blp",
	["ERP"] = "Interface\\ICONS\\Spell_Shadow_SummonSuccubus.blp",
	["Druid"] = "Interface\\ICONS\\Ability_Druid_ForceofNature.blp",
	["Arbre"] = "Interface\\ICONS\\Ability_Druid_ManaTree.blp",
	["Boum"] = "Interface\\ICONS\\INV_Gizmo_SuperSapperCharge.blp",
	["Corde"] = "Interface\\ICONS\\INV_Misc_Noose_01.blp",
	["Météorite"] = "Interface\\ICONS\\Spell_Fire_MeteorStorm.blp",
	["Technologie Gobeline"] = "Interface\\ICONS\\INV_Gizmo_TheBiggerOne.blp",
	["Fire d'Artifice"] = "Interface\\ICONS\\Ability_Mage_MissileBarrage.blp",
}